//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/cs_ez.html
halflife.wad
models/hostage.mdl
models/hostage01.mdl
models/hostage02.mdl
models/hostage03.mdl
models/hostage04.mdl
models/hostage05.mdl
models/hostage06.mdl
models/hostage07.mdl
models/hostage08.mdl
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
maps/cs_ez.bsp
maps/cs_ez.txt
